<?php
/**
 * Arayüz metinleri (menü, buton, form etiketleri).
 * Sayfa içerikleri veritabanından gelir; burada yalnızca sabit UI dizgileri tutulur.
 */
return [
    'tr' => [
        'nav.home'           => 'Ana Sayfa',
        'nav.corporate'      => 'Kurumsal',
        'nav.aboutus'        => 'Hakkımızda',
        'nav.about'          => 'Kurumsal',
        'nav.production'     => 'Üretim & Teknoloji',
        'nav.sustainability' => 'Sürdürülebilirlik',
        'nav.products'       => 'Ürünler',
        'nav.industries'     => 'Sektörler',
        'nav.global'         => 'Global',
        'nav.news'           => 'Haberler',
        'nav.contact'        => 'İletişim',

        'btn.discover'       => 'Keşfedin',
        'btn.all_products'   => 'Tüm Ürünler',
        'btn.all_news'       => 'Tüm Haberler',
        'btn.details'        => 'İncele',
        'btn.read_more'      => 'Devamını Oku',
        'btn.contact_us'     => 'Bize Ulaşın',
        'btn.send'           => 'Gönder',
        'btn.back'           => 'Geri Dön',

        'home.stats_title'   => 'Rakamlarla Işık Çelik',
        'stat.founded'       => 'Kuruluş Yılı',
        'stat.capacity'      => 'Ton / Yıl Üretim Kapasitesi',
        'stat.countries'     => 'Ülkeye İhracat',
        'stat.continents'    => 'Kıtada Varlık',
        'stat.solar'         => 'kWe Yenilenebilir Enerji',

        'form.name'          => 'Ad Soyad',
        'form.email'         => 'E-posta',
        'form.phone'         => 'Telefon',
        'form.subject'       => 'Konu',
        'form.message'       => 'Mesajınız',
        'form.success'       => 'Mesajınız başarıyla iletildi. En kısa sürede size dönüş yapacağız.',
        'form.error'         => 'Lütfen zorunlu alanları doldurun.',
        'form.required'      => 'zorunlu alan',

        'contact.address'    => 'Adres',
        'contact.phone'      => 'Telefon',
        'contact.email'      => 'E-posta',
        'contact.form_title' => 'Bize Yazın',
        'contact.info_title' => 'İletişim Bilgileri',

        'news.published'     => 'Yayın Tarihi',
        'news.latest'        => 'Son Haberler',
        'news.empty'         => 'Henüz haber eklenmemiş.',

        'products.title'     => 'Ürün Gruplarımız',
        'products.related'   => 'Diğer Ürünler',
        'industries.title'   => 'Hizmet Verdiğimiz Sektörler',

        'shop.search'        => 'Ürün ara…',
        'shop.categories'    => 'Kategoriler',
        'shop.all'           => 'Tüm Ürünler',
        'shop.count'         => 'ürün',
        'shop.noresult'      => 'Aramanızla eşleşen ürün bulunamadı.',
        'shop.category'      => 'Kategori',
        'btn.quote'          => 'Teklif İste',

        'footer.slogan'      => 'Güçlü Altyapı. Sürdürülebilir Üretim. Küresel Vizyon.',
        'footer.quicklinks'  => 'Hızlı Erişim',
        'footer.products'    => 'Ürünler',
        'footer.contact'     => 'İletişim',
        'footer.rights'      => 'Tüm hakları saklıdır.',

        'meta.suffix'        => 'Işık Çelik',
        'notfound.title'     => 'Sayfa Bulunamadı',
        'notfound.text'      => 'Aradığınız sayfa taşınmış veya kaldırılmış olabilir.',
        'notfound.home'      => 'Ana Sayfaya Dön',
        'breadcrumb.home'    => 'Ana Sayfa',
        'scroll.down'        => 'Aşağı Kaydırın',
        'since'              => "1965'ten beri",
    ],
    'en' => [
        'nav.home'           => 'Home',
        'nav.corporate'      => 'Corporate',
        'nav.aboutus'        => 'About Us',
        'nav.about'          => 'About Us',
        'nav.production'     => 'Production & Technology',
        'nav.sustainability' => 'Sustainability',
        'nav.products'       => 'Products',
        'nav.industries'     => 'Industries',
        'nav.global'         => 'Global',
        'nav.news'           => 'News',
        'nav.contact'        => 'Contact',

        'btn.discover'       => 'Discover',
        'btn.all_products'   => 'All Products',
        'btn.all_news'       => 'All News',
        'btn.details'        => 'View',
        'btn.read_more'      => 'Read More',
        'btn.contact_us'     => 'Contact Us',
        'btn.send'           => 'Send',
        'btn.back'           => 'Go Back',

        'home.stats_title'   => 'Işık Çelik in Numbers',
        'stat.founded'       => 'Founded',
        'stat.capacity'      => 'Tons / Year Production Capacity',
        'stat.countries'     => 'Countries Exported To',
        'stat.continents'    => 'Continents',
        'stat.solar'         => 'kWe Renewable Energy',

        'form.name'          => 'Full Name',
        'form.email'         => 'Email',
        'form.phone'         => 'Phone',
        'form.subject'       => 'Subject',
        'form.message'       => 'Your Message',
        'form.success'       => 'Your message has been sent successfully. We will get back to you shortly.',
        'form.error'         => 'Please fill in the required fields.',
        'form.required'      => 'required field',

        'contact.address'    => 'Address',
        'contact.phone'      => 'Phone',
        'contact.email'      => 'Email',
        'contact.form_title' => 'Write to Us',
        'contact.info_title' => 'Contact Information',

        'news.published'     => 'Published',
        'news.latest'        => 'Latest News',
        'news.empty'         => 'No news published yet.',

        'products.title'     => 'Our Product Groups',
        'products.related'   => 'Other Products',
        'industries.title'   => 'Industries We Serve',

        'shop.search'        => 'Search products…',
        'shop.categories'    => 'Categories',
        'shop.all'           => 'All Products',
        'shop.count'         => 'products',
        'shop.noresult'      => 'No products match your search.',
        'shop.category'      => 'Category',
        'btn.quote'          => 'Request a Quote',

        'footer.slogan'      => 'Strong Infrastructure. Sustainable Manufacturing. Global Vision.',
        'footer.quicklinks'  => 'Quick Links',
        'footer.products'    => 'Products',
        'footer.contact'     => 'Contact',
        'footer.rights'      => 'All rights reserved.',

        'meta.suffix'        => 'Işık Çelik',
        'notfound.title'     => 'Page Not Found',
        'notfound.text'      => 'The page you are looking for may have been moved or removed.',
        'notfound.home'      => 'Back to Home',
        'breadcrumb.home'    => 'Home',
        'scroll.down'        => 'Scroll Down',
        'since'              => 'Since 1965',
    ],
];
